version: '3'

services:
  apt-cacher-ng:
    build: .
    hostname: apt-cacher-ng
    container_name: apt-cacher-ng
    ports:
      - 3142:3142/tcp
    environment:
      TZ: "America/Chicago"
    volumes:
      - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
    restart: always
