# validate YAML
# https://codebeautify.org/yaml-validator

on:
  push:
    branches:
      - master

name: Build Docker Image

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker
        id: docker_build
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ghcr.io/firefly2442/docker-apt-cacher-ng:latest
          platforms: linux/amd64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/firefly2442/docker-apt-cacher-ng:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'